### ISSUE TITLE
Is a production grade React app feasible without redux?

### ISSUE THREAD

**Issue by jasan-s** [krawaller/reduxfirebasedemo#3]
this is more of a question than a issue. Im a react newbie and through research have decided to use firebase as backend for a MVP for an app. I m wondering, as to if i really need to use redux, or can i just get away with firebase and react. You seemed to use firebase + redux in this sample react app. Can you point out why one would need to use redux/flux for that matter to make an react app if one is using firebase as a backend. Thanks in advance

**Comment by NightTrek** [comment]
I mean it is possible but redux is definitely the best way to get state passed across your whole app. with the introduction of react hooks there is not a way to do it using useEffect but its more complex to implement
